// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pinvgauss_export
double pinvgauss_export(double x, double a, double b);
RcppExport SEXP _cobin_pinvgauss_export(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(pinvgauss_export(x, a, b));
    return rcpp_result_gen;
END_RCPP
}
// pgig_onehalf_export
double pgig_onehalf_export(double x, double a, double b);
RcppExport SEXP _cobin_pgig_onehalf_export(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(pgig_onehalf_export(x, a, b));
    return rcpp_result_gen;
END_RCPP
}
// pgig_negonehalf_export
double pgig_negonehalf_export(double x, double a, double b);
RcppExport SEXP _cobin_pgig_negonehalf_export(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(pgig_negonehalf_export(x, a, b));
    return rcpp_result_gen;
END_RCPP
}
// rkgcpp
NumericVector rkgcpp(int n, NumericVector b, NumericVector c);
RcppExport SEXP _cobin_rkgcpp(SEXP nSEXP, SEXP bSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(rkgcpp(n, b, c));
    return rcpp_result_gen;
END_RCPP
}
// rinvgauss_mulambda_export
NumericVector rinvgauss_mulambda_export(int n, double mu, double lambda);
RcppExport SEXP _cobin_rinvgauss_mulambda_export(SEXP nSEXP, SEXP muSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(rinvgauss_mulambda_export(n, mu, lambda));
    return rcpp_result_gen;
END_RCPP
}
// rgig_negonehalf_export
NumericVector rgig_negonehalf_export(int n, double a, double b);
RcppExport SEXP _cobin_rgig_negonehalf_export(SEXP nSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rgig_negonehalf_export(n, a, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cobin_pinvgauss_export", (DL_FUNC) &_cobin_pinvgauss_export, 3},
    {"_cobin_pgig_onehalf_export", (DL_FUNC) &_cobin_pgig_onehalf_export, 3},
    {"_cobin_pgig_negonehalf_export", (DL_FUNC) &_cobin_pgig_negonehalf_export, 3},
    {"_cobin_rkgcpp", (DL_FUNC) &_cobin_rkgcpp, 3},
    {"_cobin_rinvgauss_mulambda_export", (DL_FUNC) &_cobin_rinvgauss_mulambda_export, 3},
    {"_cobin_rgig_negonehalf_export", (DL_FUNC) &_cobin_rgig_negonehalf_export, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_cobin(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
