## usethis namespace: start
#' @importFrom methods as
#' @importFrom Rcpp sourceCpp
#' @importFrom stats .getXlevels
#' @importFrom stats dnbinom
#' @importFrom stats fitted
#' @importFrom stats glm.control
#' @importFrom stats integrate
#' @importFrom stats is.empty.model
#' @importFrom stats lm
#' @importFrom stats make.link
#' @importFrom stats model.extract
#' @importFrom stats model.matrix
#' @importFrom stats model.offset
#' @importFrom stats model.response
#' @importFrom stats model.weights
#' @importFrom stats pgamma
#' @importFrom stats pnbinom
#' @importFrom stats pnorm
#' @importFrom stats rbeta
#' @importFrom stats rgamma
#' @importFrom stats rnbinom
#' @importFrom stats rnorm
#' @importFrom stats runif
#' @importFrom utils setTxtProgressBar
#' @importFrom utils txtProgressBar
#' @useDynLib cobin, .registration = TRUE
## usethis namespace: end
NULL
